In [10]:
import pandas as pd

In [11]:
universe = pd.read_excel("/Users/filipporonzino/Downloads/universe.xlsx", sheet_name="Unified")

In [12]:
universe

,NaN,id().ORIG_IDS:0,id().ORIG_IDS:1,id(),security_des(),DATES,undl_ticker().EXERCISE_TYPE,undl_ticker().EXPIRE_DT,undl_ticker().PUT_CALL,undl_ticker().STRIKE_PX,undl_ticker()
0,BBG01RN5KQ84,G9F6 Comdty,G9A Comdty,BBG01RN5KQ84,G9F6C 71.38 COMB,2025-01-28,European,2026-01-30,Call,71.38,G9F6 Comdty
1,BBG01RN5KQ75,G9F6 Comdty,G9A Comdty,BBG01RN5KQ75,G9F6C 71.38 ELEC,2025-01-28,European,2026-01-30,Call,71.38,G9F6 Comdty
2,BBG01RN5KQ93,G9F6 Comdty,G9A Comdty,BBG01RN5KQ93,G9F6C 71.38 PIT,2025-01-28,European,2026-01-30,Call,71.38,G9F6 Comdty
3,BBG01RFX16D1,G9F6 Comdty,G9A Comdty,BBG01RFX16D1,G9F6C 70.1 COMB,2025-01-28,European,2026-01-30,Call,70.10,G9F6 Comdty
4,BBG01RFX16C2,G9F6 Comdty,G9A Comdty,BBG01RFX16C2,G9F6C 70.1 ELEC,2025-01-28,European,2026-01-30,Call,70.10,G9F6 Comdty
...,...,...,...,...,...,...,...,...,...,...,...
1273,BBG01JHHH164,G9Z7 Comdty,G9A Comdty,BBG01JHHH164,G9Z7C 70 COMB,2025-01-28,European,2027-12-31,Call,70.00,G9Z7 Comdty
1274,BBG01JHHH155,G9Z7 Comdty,G9A Comdty,BBG01JHHH155,G9Z7C 70 ELEC,2025-01-28,European,2027-12-31,Call,70.00,G9Z7 Comdty
1275,BBG01QLL0064,G9Z7 Comdty,G9A Comdty,BBG01QLL0064,G9Z7C 75 PIT,2025-01-28,European,2027-12-31,Call,75.00,G9Z7 Comdty
1276,BBG01QLL0037,G9Z7 Comdty,G9A Comdty,BBG01QLL0037,G9Z7C 75 ELEC,2025-01-28,European,2027-12-31,Call,75.00,G9Z7 Comdty
1277,BBG01QLL0046,G9Z7 Comdty,G9A Comdty,BBG01QLL0046,G9Z7C 75 COMB,2025-01-28,European,2027-12-31,Call,75.00,G9Z7 Comdty

In [13]:
universe = universe.iloc[:, 1:]

In [14]:
universe

,id().ORIG_IDS:0,id().ORIG_IDS:1,id(),security_des(),DATES,undl_ticker().EXERCISE_TYPE,undl_ticker().EXPIRE_DT,undl_ticker().PUT_CALL,undl_ticker().STRIKE_PX,undl_ticker()
0,G9F6 Comdty,G9A Comdty,BBG01RN5KQ84,G9F6C 71.38 COMB,2025-01-28,European,2026-01-30,Call,71.38,G9F6 Comdty
1,G9F6 Comdty,G9A Comdty,BBG01RN5KQ75,G9F6C 71.38 ELEC,2025-01-28,European,2026-01-30,Call,71.38,G9F6 Comdty
2,G9F6 Comdty,G9A Comdty,BBG01RN5KQ93,G9F6C 71.38 PIT,2025-01-28,European,2026-01-30,Call,71.38,G9F6 Comdty
3,G9F6 Comdty,G9A Comdty,BBG01RFX16D1,G9F6C 70.1 COMB,2025-01-28,European,2026-01-30,Call,70.10,G9F6 Comdty
4,G9F6 Comdty,G9A Comdty,BBG01RFX16C2,G9F6C 70.1 ELEC,2025-01-28,European,2026-01-30,Call,70.10,G9F6 Comdty
...,...,...,...,...,...,...,...,...,...,...
1273,G9Z7 Comdty,G9A Comdty,BBG01JHHH164,G9Z7C 70 COMB,2025-01-28,European,2027-12-31,Call,70.00,G9Z7 Comdty
1274,G9Z7 Comdty,G9A Comdty,BBG01JHHH155,G9Z7C 70 ELEC,2025-01-28,European,2027-12-31,Call,70.00,G9Z7 Comdty
1275,G9Z7 Comdty,G9A Comdty,BBG01QLL0064,G9Z7C 75 PIT,2025-01-28,European,2027-12-31,Call,75.00,G9Z7 Comdty
1276,G9Z7 Comdty,G9A Comdty,BBG01QLL0037,G9Z7C 75 ELEC,2025-01-28,European,2027-12-31,Call,75.00,G9Z7 Comdty
1277,G9Z7 Comdty,G9A Comdty,BBG01QLL0046,G9Z7C 75 COMB,2025-01-28,European,2027-12-31,Call,75.00,G9Z7 Comdty