In [2]:
import pandas as pd

In [3]:
universe = pd.read_excel("/Users/filipporonzino/Downloads/universe.xlsx", sheet_name="Unified")

In [4]:
universe

,NaN,id().ORIG_IDS:0,id().ORIG_IDS:1,id(),security_des(),DATES,undl_ticker().EXERCISE_TYPE,undl_ticker().EXPIRE_DT,undl_ticker().PUT_CALL,undl_ticker().STRIKE_PX,undl_ticker()
0,BBG01RN5KQ84,G9F6 Comdty,G9A Comdty,BBG01RN5KQ84,G9F6C 71.38 COMB,2025-01-28,European,2026-01-30,Call,71.38,G9F6 Comdty
1,BBG01RN5KQ75,G9F6 Comdty,G9A Comdty,BBG01RN5KQ75,G9F6C 71.38 ELEC,2025-01-28,European,2026-01-30,Call,71.38,G9F6 Comdty
2,BBG01RN5KQ93,G9F6 Comdty,G9A Comdty,BBG01RN5KQ93,G9F6C 71.38 PIT,2025-01-28,European,2026-01-30,Call,71.38,G9F6 Comdty
3,BBG01RFX16D1,G9F6 Comdty,G9A Comdty,BBG01RFX16D1,G9F6C 70.1 COMB,2025-01-28,European,2026-01-30,Call,70.10,G9F6 Comdty
4,BBG01RFX16C2,G9F6 Comdty,G9A Comdty,BBG01RFX16C2,G9F6C 70.1 ELEC,2025-01-28,European,2026-01-30,Call,70.10,G9F6 Comdty
...,...,...,...,...,...,...,...,...,...,...,...
1273,BBG01JHHH164,G9Z7 Comdty,G9A Comdty,BBG01JHHH164,G9Z7C 70 COMB,2025-01-28,European,2027-12-31,Call,70.00,G9Z7 Comdty
1274,BBG01JHHH155,G9Z7 Comdty,G9A Comdty,BBG01JHHH155,G9Z7C 70 ELEC,2025-01-28,European,2027-12-31,Call,70.00,G9Z7 Comdty
1275,BBG01QLL0064,G9Z7 Comdty,G9A Comdty,BBG01QLL0064,G9Z7C 75 PIT,2025-01-28,European,2027-12-31,Call,75.00,G9Z7 Comdty
1276,BBG01QLL0037,G9Z7 Comdty,G9A Comdty,BBG01QLL0037,G9Z7C 75 ELEC,2025-01-28,European,2027-12-31,Call,75.00,G9Z7 Comdty
1277,BBG01QLL0046,G9Z7 Comdty,G9A Comdty,BBG01QLL0046,G9Z7C 75 COMB,2025-01-28,European,2027-12-31,Call,75.00,G9Z7 Comdty

In [5]:
universe = universe.iloc[:, 1:]

In [6]:
universe

,id().ORIG_IDS:0,id().ORIG_IDS:1,id(),security_des(),DATES,undl_ticker().EXERCISE_TYPE,undl_ticker().EXPIRE_DT,undl_ticker().PUT_CALL,undl_ticker().STRIKE_PX,undl_ticker()
0,G9F6 Comdty,G9A Comdty,BBG01RN5KQ84,G9F6C 71.38 COMB,2025-01-28,European,2026-01-30,Call,71.38,G9F6 Comdty
1,G9F6 Comdty,G9A Comdty,BBG01RN5KQ75,G9F6C 71.38 ELEC,2025-01-28,European,2026-01-30,Call,71.38,G9F6 Comdty
2,G9F6 Comdty,G9A Comdty,BBG01RN5KQ93,G9F6C 71.38 PIT,2025-01-28,European,2026-01-30,Call,71.38,G9F6 Comdty
3,G9F6 Comdty,G9A Comdty,BBG01RFX16D1,G9F6C 70.1 COMB,2025-01-28,European,2026-01-30,Call,70.10,G9F6 Comdty
4,G9F6 Comdty,G9A Comdty,BBG01RFX16C2,G9F6C 70.1 ELEC,2025-01-28,European,2026-01-30,Call,70.10,G9F6 Comdty
...,...,...,...,...,...,...,...,...,...,...
1273,G9Z7 Comdty,G9A Comdty,BBG01JHHH164,G9Z7C 70 COMB,2025-01-28,European,2027-12-31,Call,70.00,G9Z7 Comdty
1274,G9Z7 Comdty,G9A Comdty,BBG01JHHH155,G9Z7C 70 ELEC,2025-01-28,European,2027-12-31,Call,70.00,G9Z7 Comdty
1275,G9Z7 Comdty,G9A Comdty,BBG01QLL0064,G9Z7C 75 PIT,2025-01-28,European,2027-12-31,Call,75.00,G9Z7 Comdty
1276,G9Z7 Comdty,G9A Comdty,BBG01QLL0037,G9Z7C 75 ELEC,2025-01-28,European,2027-12-31,Call,75.00,G9Z7 Comdty
1277,G9Z7 Comdty,G9A Comdty,BBG01QLL0046,G9Z7C 75 COMB,2025-01-28,European,2027-12-31,Call,75.00,G9Z7 Comdty

In [41]:
universe = universe[universe["security_des()"].str.contains("COMB")]

In [44]:
universe["security_des()"] = universe["security_des()"].str.replace("COMB", "Comdty", regex=False)

/var/folders/l4/fwn11xh17pb5ryvd5h_w9p8r0000gn/T/ipykernel_40358/3417284241.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  universe["security_des()"] = universe["security_des()"].str.replace("COMB", "Comdty", regex=False)

In [45]:
universe

,id().ORIG_IDS:0,id().ORIG_IDS:1,id(),security_des(),DATES,undl_ticker().EXERCISE_TYPE,undl_ticker().EXPIRE_DT,undl_ticker().PUT_CALL,undl_ticker().STRIKE_PX,undl_ticker()
0,G9F6 Comdty,G9A Comdty,BBG01RN5KQ84,G9F6C 71.38 Comdty,2025-01-28,European,2026-01-30,Call,71.38,G9F6 Comdty
3,G9F6 Comdty,G9A Comdty,BBG01RFX16D1,G9F6C 70.1 Comdty,2025-01-28,European,2026-01-30,Call,70.10,G9F6 Comdty
6,G9F6 Comdty,G9A Comdty,BBG01R3Z3GP2,G9F6C 71.25 Comdty,2025-01-28,European,2026-01-30,Call,71.25,G9F6 Comdty
9,G9F6 Comdty,G9A Comdty,BBG01QZGMPR8,G9F6C 72.35 Comdty,2025-01-28,European,2026-01-30,Call,72.35,G9F6 Comdty
12,G9F6 Comdty,G9A Comdty,BBG01MS5CJS3,G9F6C 76.55 Comdty,2025-01-28,European,2026-01-30,Call,76.55,G9F6 Comdty
...,...,...,...,...,...,...,...,...,...,...
1265,G9V7 Comdty,G9A Comdty,BBG01QS16BL4,G9V7C 69 Comdty,2025-01-28,European,2027-10-29,Call,69.00,G9V7 Comdty
1267,G9X7 Comdty,G9A Comdty,BBG01JHHGX01,G9X7C 70 Comdty,2025-01-28,European,2027-11-30,Call,70.00,G9X7 Comdty
1271,G9X7 Comdty,G9A Comdty,BBG01QLKZXF6,G9X7C 75 Comdty,2025-01-28,European,2027-11-30,Call,75.00,G9X7 Comdty
1273,G9Z7 Comdty,G9A Comdty,BBG01JHHH164,G9Z7C 70 Comdty,2025-01-28,European,2027-12-31,Call,70.00,G9Z7 Comdty
1277,G9Z7 Comdty,G9A Comdty,BBG01QLL0046,G9Z7C 75 Comdty,2025-01-28,European,2027-12-31,Call,75.00,G9Z7 Comdty

In [34]:
# Load the Excel file
xls = pd.ExcelFile("/Users/filipporonzino/Downloads/prices.xlsx")
df_full = pd.read_excel(xls, sheet_name="Sheet1", header=None)

# Identify columns for tickers and prices
ticker_columns = list(range(2, df_full.shape[1], 3))  # C5, F5, I5, ...
price_columns = list(range(3, df_full.shape[1], 3))  # D6, G6, J6, ...

# Extract tickers and clean names (remove "Comdty" and extra spaces)
tickers = df_full.iloc[4, ticker_columns].astype(str).tolist()

# Extract date column (C7 downwards)
date_column = df_full.iloc[6:, 2].reset_index(drop=True)  # Column C (index 2)

# Extract price data (D7 downwards)
prices = df_full.iloc[6:, price_columns].reset_index(drop=True)

# Combine into DataFrame
df_final = pd.concat([date_column, prices], axis=1)

# Assign column names
df_final.columns = ["Date"] + tickers

# Convert Date column to datetime
df_final["Date"] = pd.to_datetime(df_final["Date"], errors="coerce")

# Convert price columns to numeric
df_final.iloc[:, 1:] = df_final.iloc[:, 1:].apply(pd.to_numeric, errors="coerce")

# Display cleaned DataFrame
df_final

,Date,G9F6C 71.38 Comdty,G9F6C 70.1 Comdty,G9F6C 71.25 Comdty,G9F6C 72.35 Comdty,G9F6C 76.55 Comdty,G9F6C 77.25 Comdty,G9F6C 81.25 Comdty,G9F6C 79.25 Comdty,G9F6C 78 Comdty,...,G9U7C 71.1 Comdty,G9U7C 69 Comdty,G9V7C 70 Comdty,G9V7C 75 Comdty,G9V7C 71.1 Comdty,G9V7C 69 Comdty,G9X7C 70 Comdty,G9X7C 75 Comdty,G9Z7C 70 Comdty,G9Z7C 75 Comdty
0,2024-09-02,NaN,NaN,NaN,NaN,4.55,4.33,3.24,3.75,4.1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2024-09-03,NaN,NaN,NaN,NaN,3.87,3.68,2.76,3.18,3.48,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2024-09-04,NaN,NaN,NaN,NaN,3.87,3.68,2.78,3.2,3.49,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2024-09-05,NaN,NaN,NaN,NaN,3.88,3.68,2.75,3.18,3.49,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2024-09-06,NaN,NaN,NaN,NaN,3.48,3.31,2.47,2.85,3.13,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
415,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
416,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
417,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
418,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
419,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [35]:
df_final = df_final[(df_final["Date"] >= df_final["Date"].min()) & (df_final["Date"] <= df_final["Date"].max())]

In [36]:
df_final

,Date,G9F6C 71.38 Comdty,G9F6C 70.1 Comdty,G9F6C 71.25 Comdty,G9F6C 72.35 Comdty,G9F6C 76.55 Comdty,G9F6C 77.25 Comdty,G9F6C 81.25 Comdty,G9F6C 79.25 Comdty,G9F6C 78 Comdty,...,G9U7C 71.1 Comdty,G9U7C 69 Comdty,G9V7C 70 Comdty,G9V7C 75 Comdty,G9V7C 71.1 Comdty,G9V7C 69 Comdty,G9X7C 70 Comdty,G9X7C 75 Comdty,G9Z7C 70 Comdty,G9Z7C 75 Comdty
0,2024-09-02,NaN,NaN,NaN,NaN,4.55,4.33,3.24,3.75,4.1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2024-09-03,NaN,NaN,NaN,NaN,3.87,3.68,2.76,3.18,3.48,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2024-09-04,NaN,NaN,NaN,NaN,3.87,3.68,2.78,3.2,3.49,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2024-09-05,NaN,NaN,NaN,NaN,3.88,3.68,2.75,3.18,3.49,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2024-09-06,NaN,NaN,NaN,NaN,3.48,3.31,2.47,2.85,3.13,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102,2025-01-22,5.95,6.55,6.01,5.53,3.97,3.75,2.7,3.18,3.53,...,6.64,7.49,7.13,5.35,6.7,7.54,7.19,5.43,7.22,5.47
103,2025-01-23,5.79,6.37,5.84,5.37,3.83,3.62,2.59,3.06,3.4,...,6.61,7.46,7.1,5.32,6.67,7.51,7.17,5.4,7.2,5.45
104,2025-01-24,5.55,6.15,5.61,5.13,3.64,3.44,2.44,2.9,3.22,...,6.44,7.28,6.92,5.17,6.5,7.32,6.98,5.25,7.01,5.29
105,2025-01-27,5.14,5.67,5.19,4.76,3.37,3.17,2.25,2.67,2.98,...,6.22,7.02,6.69,5.0,6.28,7.08,6.76,5.08,6.81,5.14
106,2025-01-28,5.14,5.67,5.19,4.76,3.37,3.17,2.25,2.67,2.98,...,6.22,7.02,6.69,5.0,6.28,7.08,6.76,5.08,6.81,5.14

In [37]:
# keep just columns with at least 50 percent of non-NaN values
df_final = df_final.dropna(axis=1, thresh=0.5*len(df_final))

In [38]:
df_final

,Date,G9F6C 76.55 Comdty,G9F6C 77.25 Comdty,G9F6C 81.25 Comdty,G9F6C 79.25 Comdty,G9F6C 78 Comdty,G9F6C 77 Comdty,G9F6C 76 Comdty,G9F6C 69.5 Comdty,G9F6C 74 Comdty,...,G9U7C 70 Comdty,G9U7C 75 Comdty,G9U7C 71.1 Comdty,G9U7C 69 Comdty,G9V7C 70 Comdty,G9V7C 75 Comdty,G9V7C 71.1 Comdty,G9V7C 69 Comdty,G9X7C 75 Comdty,G9Z7C 75 Comdty
0,2024-09-02,4.55,4.33,3.24,3.75,4.1,4.4,NaN,7.33,5.44,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2024-09-03,3.87,3.68,2.76,3.18,3.48,3.74,NaN,6.36,4.65,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2024-09-04,3.87,3.68,2.78,3.2,3.49,3.75,NaN,6.31,4.64,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2024-09-05,3.88,3.68,2.75,3.18,3.49,3.75,NaN,6.38,4.66,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2024-09-06,3.48,3.31,2.47,2.85,3.13,3.37,NaN,5.82,4.21,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102,2025-01-22,3.97,3.75,2.7,3.18,3.53,3.83,4.15,6.84,4.86,...,7.08,5.28,6.64,7.49,7.13,5.35,6.7,7.54,5.43,5.47
103,2025-01-23,3.83,3.62,2.59,3.06,3.4,3.69,4.01,6.66,4.72,...,7.05,5.26,6.61,7.46,7.1,5.32,6.67,7.51,5.4,5.45
104,2025-01-24,3.64,3.44,2.44,2.9,3.22,3.51,3.81,6.43,4.49,...,6.87,5.11,6.44,7.28,6.92,5.17,6.5,7.32,5.25,5.29
105,2025-01-27,3.37,3.17,2.25,2.67,2.98,3.24,3.53,5.93,4.16,...,6.63,4.94,6.22,7.02,6.69,5.0,6.28,7.08,5.08,5.14
106,2025-01-28,3.37,3.17,2.25,2.67,2.98,3.24,3.53,5.93,4.16,...,6.63,4.94,6.22,7.02,6.69,5.0,6.28,7.08,5.08,5.14

In [46]:
universe

,id().ORIG_IDS:0,id().ORIG_IDS:1,id(),security_des(),DATES,undl_ticker().EXERCISE_TYPE,undl_ticker().EXPIRE_DT,undl_ticker().PUT_CALL,undl_ticker().STRIKE_PX,undl_ticker()
0,G9F6 Comdty,G9A Comdty,BBG01RN5KQ84,G9F6C 71.38 Comdty,2025-01-28,European,2026-01-30,Call,71.38,G9F6 Comdty
3,G9F6 Comdty,G9A Comdty,BBG01RFX16D1,G9F6C 70.1 Comdty,2025-01-28,European,2026-01-30,Call,70.10,G9F6 Comdty
6,G9F6 Comdty,G9A Comdty,BBG01R3Z3GP2,G9F6C 71.25 Comdty,2025-01-28,European,2026-01-30,Call,71.25,G9F6 Comdty
9,G9F6 Comdty,G9A Comdty,BBG01QZGMPR8,G9F6C 72.35 Comdty,2025-01-28,European,2026-01-30,Call,72.35,G9F6 Comdty
12,G9F6 Comdty,G9A Comdty,BBG01MS5CJS3,G9F6C 76.55 Comdty,2025-01-28,European,2026-01-30,Call,76.55,G9F6 Comdty
...,...,...,...,...,...,...,...,...,...,...
1265,G9V7 Comdty,G9A Comdty,BBG01QS16BL4,G9V7C 69 Comdty,2025-01-28,European,2027-10-29,Call,69.00,G9V7 Comdty
1267,G9X7 Comdty,G9A Comdty,BBG01JHHGX01,G9X7C 70 Comdty,2025-01-28,European,2027-11-30,Call,70.00,G9X7 Comdty
1271,G9X7 Comdty,G9A Comdty,BBG01QLKZXF6,G9X7C 75 Comdty,2025-01-28,European,2027-11-30,Call,75.00,G9X7 Comdty
1273,G9Z7 Comdty,G9A Comdty,BBG01JHHH164,G9Z7C 70 Comdty,2025-01-28,European,2027-12-31,Call,70.00,G9Z7 Comdty
1277,G9Z7 Comdty,G9A Comdty,BBG01QLL0046,G9Z7C 75 Comdty,2025-01-28,European,2027-12-31,Call,75.00,G9Z7 Comdty