In [ ]:
import pandas as pd

In [1]:
universe = pd.read_excel("/Users/filipporonzino/Downloads/universe.xlsx", sheet_name="Unified")

NameError: name 'pd' is not defined

In [ ]:
universe

,NaN,id().ORIG_IDS:0,id().ORIG_IDS:1,id(),security_des(),DATES,undl_ticker().EXERCISE_TYPE,undl_ticker().EXPIRE_DT,undl_ticker().PUT_CALL,undl_ticker().STRIKE_PX,undl_ticker()
0,BBG01RN5KQ84,G9F6 Comdty,G9A Comdty,BBG01RN5KQ84,G9F6C 71.38 COMB,2025-01-28,European,2026-01-30,Call,71.38,G9F6 Comdty
1,BBG01RN5KQ75,G9F6 Comdty,G9A Comdty,BBG01RN5KQ75,G9F6C 71.38 ELEC,2025-01-28,European,2026-01-30,Call,71.38,G9F6 Comdty
2,BBG01RN5KQ93,G9F6 Comdty,G9A Comdty,BBG01RN5KQ93,G9F6C 71.38 PIT,2025-01-28,European,2026-01-30,Call,71.38,G9F6 Comdty
3,BBG01RFX16D1,G9F6 Comdty,G9A Comdty,BBG01RFX16D1,G9F6C 70.1 COMB,2025-01-28,European,2026-01-30,Call,70.10,G9F6 Comdty
4,BBG01RFX16C2,G9F6 Comdty,G9A Comdty,BBG01RFX16C2,G9F6C 70.1 ELEC,2025-01-28,European,2026-01-30,Call,70.10,G9F6 Comdty
...,...,...,...,...,...,...,...,...,...,...,...
1273,BBG01JHHH164,G9Z7 Comdty,G9A Comdty,BBG01JHHH164,G9Z7C 70 COMB,2025-01-28,European,2027-12-31,Call,70.00,G9Z7 Comdty
1274,BBG01JHHH155,G9Z7 Comdty,G9A Comdty,BBG01JHHH155,G9Z7C 70 ELEC,2025-01-28,European,2027-12-31,Call,70.00,G9Z7 Comdty
1275,BBG01QLL0064,G9Z7 Comdty,G9A Comdty,BBG01QLL0064,G9Z7C 75 PIT,2025-01-28,European,2027-12-31,Call,75.00,G9Z7 Comdty
1276,BBG01QLL0037,G9Z7 Comdty,G9A Comdty,BBG01QLL0037,G9Z7C 75 ELEC,2025-01-28,European,2027-12-31,Call,75.00,G9Z7 Comdty
1277,BBG01QLL0046,G9Z7 Comdty,G9A Comdty,BBG01QLL0046,G9Z7C 75 COMB,2025-01-28,European,2027-12-31,Call,75.00,G9Z7 Comdty

In [ ]:
universe = universe.iloc[:, 1:]

In [ ]:
universe

,id().ORIG_IDS:0,id().ORIG_IDS:1,id(),security_des(),DATES,undl_ticker().EXERCISE_TYPE,undl_ticker().EXPIRE_DT,undl_ticker().PUT_CALL,undl_ticker().STRIKE_PX,undl_ticker()
0,G9F6 Comdty,G9A Comdty,BBG01RN5KQ84,G9F6C 71.38 COMB,2025-01-28,European,2026-01-30,Call,71.38,G9F6 Comdty
1,G9F6 Comdty,G9A Comdty,BBG01RN5KQ75,G9F6C 71.38 ELEC,2025-01-28,European,2026-01-30,Call,71.38,G9F6 Comdty
2,G9F6 Comdty,G9A Comdty,BBG01RN5KQ93,G9F6C 71.38 PIT,2025-01-28,European,2026-01-30,Call,71.38,G9F6 Comdty
3,G9F6 Comdty,G9A Comdty,BBG01RFX16D1,G9F6C 70.1 COMB,2025-01-28,European,2026-01-30,Call,70.10,G9F6 Comdty
4,G9F6 Comdty,G9A Comdty,BBG01RFX16C2,G9F6C 70.1 ELEC,2025-01-28,European,2026-01-30,Call,70.10,G9F6 Comdty
...,...,...,...,...,...,...,...,...,...,...
1273,G9Z7 Comdty,G9A Comdty,BBG01JHHH164,G9Z7C 70 COMB,2025-01-28,European,2027-12-31,Call,70.00,G9Z7 Comdty
1274,G9Z7 Comdty,G9A Comdty,BBG01JHHH155,G9Z7C 70 ELEC,2025-01-28,European,2027-12-31,Call,70.00,G9Z7 Comdty
1275,G9Z7 Comdty,G9A Comdty,BBG01QLL0064,G9Z7C 75 PIT,2025-01-28,European,2027-12-31,Call,75.00,G9Z7 Comdty
1276,G9Z7 Comdty,G9A Comdty,BBG01QLL0037,G9Z7C 75 ELEC,2025-01-28,European,2027-12-31,Call,75.00,G9Z7 Comdty
1277,G9Z7 Comdty,G9A Comdty,BBG01QLL0046,G9Z7C 75 COMB,2025-01-28,European,2027-12-31,Call,75.00,G9Z7 Comdty

In [ ]:
universe = universe[universe["security_des()"].str.contains("COMB")]

In [ ]:
universe["security_des()"] = universe["security_des()"].str.replace("COMB", "Comdty", regex=False)

/var/folders/l4/fwn11xh17pb5ryvd5h_w9p8r0000gn/T/ipykernel_7001/3417284241.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  universe["security_des()"] = universe["security_des()"].str.replace("COMB", "Comdty", regex=False)

In [ ]:
universe

,id().ORIG_IDS:0,id().ORIG_IDS:1,id(),security_des(),DATES,undl_ticker().EXERCISE_TYPE,undl_ticker().EXPIRE_DT,undl_ticker().PUT_CALL,undl_ticker().STRIKE_PX,undl_ticker()
0,G9F6 Comdty,G9A Comdty,BBG01RN5KQ84,G9F6C 71.38 Comdty,2025-01-28,European,2026-01-30,Call,71.38,G9F6 Comdty
3,G9F6 Comdty,G9A Comdty,BBG01RFX16D1,G9F6C 70.1 Comdty,2025-01-28,European,2026-01-30,Call,70.10,G9F6 Comdty
6,G9F6 Comdty,G9A Comdty,BBG01R3Z3GP2,G9F6C 71.25 Comdty,2025-01-28,European,2026-01-30,Call,71.25,G9F6 Comdty
9,G9F6 Comdty,G9A Comdty,BBG01QZGMPR8,G9F6C 72.35 Comdty,2025-01-28,European,2026-01-30,Call,72.35,G9F6 Comdty
12,G9F6 Comdty,G9A Comdty,BBG01MS5CJS3,G9F6C 76.55 Comdty,2025-01-28,European,2026-01-30,Call,76.55,G9F6 Comdty
...,...,...,...,...,...,...,...,...,...,...
1265,G9V7 Comdty,G9A Comdty,BBG01QS16BL4,G9V7C 69 Comdty,2025-01-28,European,2027-10-29,Call,69.00,G9V7 Comdty
1267,G9X7 Comdty,G9A Comdty,BBG01JHHGX01,G9X7C 70 Comdty,2025-01-28,European,2027-11-30,Call,70.00,G9X7 Comdty
1271,G9X7 Comdty,G9A Comdty,BBG01QLKZXF6,G9X7C 75 Comdty,2025-01-28,European,2027-11-30,Call,75.00,G9X7 Comdty
1273,G9Z7 Comdty,G9A Comdty,BBG01JHHH164,G9Z7C 70 Comdty,2025-01-28,European,2027-12-31,Call,70.00,G9Z7 Comdty
1277,G9Z7 Comdty,G9A Comdty,BBG01QLL0046,G9Z7C 75 Comdty,2025-01-28,European,2027-12-31,Call,75.00,G9Z7 Comdty

In [ ]:
# Load the Excel file
xls = pd.ExcelFile("/Users/filipporonzino/Downloads/prices.xlsx")
df_full = pd.read_excel(xls, sheet_name="Sheet1", header=None)

# Identify columns for tickers and prices
ticker_columns = list(range(2, df_full.shape[1], 3))  # C5, F5, I5, ...
price_columns = list(range(3, df_full.shape[1], 3))  # D6, G6, J6, ...

# Extract tickers and clean names (remove "Comdty" and extra spaces)
tickers = df_full.iloc[4, ticker_columns].astype(str).tolist()

# Extract date column (C7 downwards)
date_column = df_full.iloc[6:, 2].reset_index(drop=True)  # Column C (index 2)

# Extract price data (D7 downwards)
prices = df_full.iloc[6:, price_columns].reset_index(drop=True)

# Combine into DataFrame
df_final = pd.concat([date_column, prices], axis=1)

# Assign column names
df_final.columns = ["Date"] + tickers

# Convert Date column to datetime
df_final["Date"] = pd.to_datetime(df_final["Date"], errors="coerce")

# Convert price columns to numeric
df_final.iloc[:, 1:] = df_final.iloc[:, 1:].apply(pd.to_numeric, errors="coerce")

# Display cleaned DataFrame
df_final

,Date,G9F6C 71.38 Comdty,G9F6C 70.1 Comdty,G9F6C 71.25 Comdty,G9F6C 72.35 Comdty,G9F6C 76.55 Comdty,G9F6C 77.25 Comdty,G9F6C 81.25 Comdty,G9F6C 79.25 Comdty,G9F6C 78 Comdty,...,G9U7C 71.1 Comdty,G9U7C 69 Comdty,G9V7C 70 Comdty,G9V7C 75 Comdty,G9V7C 71.1 Comdty,G9V7C 69 Comdty,G9X7C 70 Comdty,G9X7C 75 Comdty,G9Z7C 70 Comdty,G9Z7C 75 Comdty
0,2024-09-02,NaN,NaN,NaN,NaN,4.55,4.33,3.24,3.75,4.1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2024-09-03,NaN,NaN,NaN,NaN,3.87,3.68,2.76,3.18,3.48,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2024-09-04,NaN,NaN,NaN,NaN,3.87,3.68,2.78,3.2,3.49,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2024-09-05,NaN,NaN,NaN,NaN,3.88,3.68,2.75,3.18,3.49,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2024-09-06,NaN,NaN,NaN,NaN,3.48,3.31,2.47,2.85,3.13,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
415,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
416,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
417,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
418,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
419,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df_final = df_final[(df_final["Date"] >= df_final["Date"].min()) & (df_final["Date"] <= df_final["Date"].max())]

In [ ]:
df_final

,Date,G9F6C 71.38 Comdty,G9F6C 70.1 Comdty,G9F6C 71.25 Comdty,G9F6C 72.35 Comdty,G9F6C 76.55 Comdty,G9F6C 77.25 Comdty,G9F6C 81.25 Comdty,G9F6C 79.25 Comdty,G9F6C 78 Comdty,...,G9U7C 71.1 Comdty,G9U7C 69 Comdty,G9V7C 70 Comdty,G9V7C 75 Comdty,G9V7C 71.1 Comdty,G9V7C 69 Comdty,G9X7C 70 Comdty,G9X7C 75 Comdty,G9Z7C 70 Comdty,G9Z7C 75 Comdty
0,2024-09-02,NaN,NaN,NaN,NaN,4.55,4.33,3.24,3.75,4.1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2024-09-03,NaN,NaN,NaN,NaN,3.87,3.68,2.76,3.18,3.48,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2024-09-04,NaN,NaN,NaN,NaN,3.87,3.68,2.78,3.2,3.49,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2024-09-05,NaN,NaN,NaN,NaN,3.88,3.68,2.75,3.18,3.49,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2024-09-06,NaN,NaN,NaN,NaN,3.48,3.31,2.47,2.85,3.13,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102,2025-01-22,5.95,6.55,6.01,5.53,3.97,3.75,2.7,3.18,3.53,...,6.64,7.49,7.13,5.35,6.7,7.54,7.19,5.43,7.22,5.47
103,2025-01-23,5.79,6.37,5.84,5.37,3.83,3.62,2.59,3.06,3.4,...,6.61,7.46,7.1,5.32,6.67,7.51,7.17,5.4,7.2,5.45
104,2025-01-24,5.55,6.15,5.61,5.13,3.64,3.44,2.44,2.9,3.22,...,6.44,7.28,6.92,5.17,6.5,7.32,6.98,5.25,7.01,5.29
105,2025-01-27,5.14,5.67,5.19,4.76,3.37,3.17,2.25,2.67,2.98,...,6.22,7.02,6.69,5.0,6.28,7.08,6.76,5.08,6.81,5.14
106,2025-01-28,5.14,5.67,5.19,4.76,3.37,3.17,2.25,2.67,2.98,...,6.22,7.02,6.69,5.0,6.28,7.08,6.76,5.08,6.81,5.14

In [ ]:
# keep just columns with at least 50 percent of non-NaN values
df_final = df_final.dropna(axis=1, thresh=0.5*len(df_final))

In [ ]:
df_final 
df_final.columns = df_final.columns.str.strip().str.replace(r'\s+', ' ', regex=True)
print(df_final.columns)

Index(['Date', 'G9F6C 76.55 Comdty', 'G9F6C 77.25 Comdty',
       'G9F6C 81.25 Comdty', 'G9F6C 79.25 Comdty', 'G9F6C 78 Comdty',
       'G9F6C 77 Comdty', 'G9F6C 76 Comdty', 'G9F6C 69.5 Comdty',
       'G9F6C 74 Comdty',
       ...
       'G9U7C 70 Comdty', 'G9U7C 75 Comdty', 'G9U7C 71.1 Comdty',
       'G9U7C 69 Comdty', 'G9V7C 70 Comdty', 'G9V7C 75 Comdty',
       'G9V7C 71.1 Comdty', 'G9V7C 69 Comdty', 'G9X7C 75 Comdty',
       'G9Z7C 75 Comdty'],
      dtype='object', length=299)

In [ ]:
universe = universe.drop(columns=["id().ORIG_IDS:0", "id().ORIG_IDS:1", "DATES"])
universe = universe.rename(columns={"id().ORIG_IDS:0": "ID", "security_des()": "SECURITY_DES", "undl_ticker().EXERCISE_TYPE": "EXERCISE_TYPE", "undl_ticker().EXPIRE_DT": "EXPIRE_DT", "undl_ticker().PUT_CALL": "PUT_CALL", "undl_ticker().STRIKE_PX": "STRIKE_PX", "undl_ticker()": "TICKER"})
universe

,id(),SECURITY_DES,EXERCISE_TYPE,EXPIRE_DT,PUT_CALL,STRIKE_PX,TICKER
0,BBG01RN5KQ84,G9F6C 71.38 Comdty,European,2026-01-30,Call,71.38,G9F6 Comdty
3,BBG01RFX16D1,G9F6C 70.1 Comdty,European,2026-01-30,Call,70.10,G9F6 Comdty
6,BBG01R3Z3GP2,G9F6C 71.25 Comdty,European,2026-01-30,Call,71.25,G9F6 Comdty
9,BBG01QZGMPR8,G9F6C 72.35 Comdty,European,2026-01-30,Call,72.35,G9F6 Comdty
12,BBG01MS5CJS3,G9F6C 76.55 Comdty,European,2026-01-30,Call,76.55,G9F6 Comdty
...,...,...,...,...,...,...,...
1265,BBG01QS16BL4,G9V7C 69 Comdty,European,2027-10-29,Call,69.00,G9V7 Comdty
1267,BBG01JHHGX01,G9X7C 70 Comdty,European,2027-11-30,Call,70.00,G9X7 Comdty
1271,BBG01QLKZXF6,G9X7C 75 Comdty,European,2027-11-30,Call,75.00,G9X7 Comdty
1273,BBG01JHHH164,G9Z7C 70 Comdty,European,2027-12-31,Call,70.00,G9Z7 Comdty
1277,BBG01QLL0046,G9Z7C 75 Comdty,European,2027-12-31,Call,75.00,G9Z7 Comdty

In [ ]:
universe["SECURITY_DES"] = universe["SECURITY_DES"].str.strip().str.replace(r'\s+', ' ', regex=True)
universe

,id(),SECURITY_DES,EXERCISE_TYPE,EXPIRE_DT,PUT_CALL,STRIKE_PX,TICKER
0,BBG01RN5KQ84,G9F6C 71.38 Comdty,European,2026-01-30,Call,71.38,G9F6 Comdty
3,BBG01RFX16D1,G9F6C 70.1 Comdty,European,2026-01-30,Call,70.10,G9F6 Comdty
6,BBG01R3Z3GP2,G9F6C 71.25 Comdty,European,2026-01-30,Call,71.25,G9F6 Comdty
9,BBG01QZGMPR8,G9F6C 72.35 Comdty,European,2026-01-30,Call,72.35,G9F6 Comdty
12,BBG01MS5CJS3,G9F6C 76.55 Comdty,European,2026-01-30,Call,76.55,G9F6 Comdty
...,...,...,...,...,...,...,...
1265,BBG01QS16BL4,G9V7C 69 Comdty,European,2027-10-29,Call,69.00,G9V7 Comdty
1267,BBG01JHHGX01,G9X7C 70 Comdty,European,2027-11-30,Call,70.00,G9X7 Comdty
1271,BBG01QLKZXF6,G9X7C 75 Comdty,European,2027-11-30,Call,75.00,G9X7 Comdty
1273,BBG01JHHH164,G9Z7C 70 Comdty,European,2027-12-31,Call,70.00,G9Z7 Comdty
1277,BBG01QLL0046,G9Z7C 75 Comdty,European,2027-12-31,Call,75.00,G9Z7 Comdty

In [ ]:
xls = pd.ExcelFile("/Users/filipporonzino/Downloads/voldata.xlsx")
df_vol = pd.read_excel(xls, sheet_name="Sheet1", header=5)
df_vol

,Dates,HIST_PUT_IMP_VOL,VOLATILITY_30D,HIST_CALL_IMP_VOL,VOLATILITY_60D,VOLATILITY_90D,VOLATILITY_10D,VOLATILITY_20D
0,2024-09-03,28.64,29.24,NaN,23.58,22.10,34.21,30.12
1,2024-09-04,29.35,29.13,NaN,23.20,22.13,34.05,29.19
2,2024-09-05,28.92,29.11,NaN,23.19,22.12,33.23,28.71
3,2024-09-06,29.11,29.57,NaN,23.49,22.37,30.44,29.16
4,2024-09-09,29.10,29.64,NaN,23.56,21.83,26.67,26.64
...,...,...,...,...,...,...,...,...
103,2025-01-30,18.33,21.20,18.32,22.82,28.98,15.41,24.16
104,2025-01-31,18.17,21.23,18.22,22.79,28.85,15.58,23.91
105,2025-02-03,16.72,21.06,16.74,22.81,28.67,15.53,24.06
106,2025-02-04,15.55,21.14,15.59,22.74,28.33,15.52,23.88
107,2025-02-05,NaN,22.13,14.65,22.64,28.55,17.69,24.65

In [ ]:


# Step 1: Extract dates from df_final
dates = df_final[["Date"]].drop_duplicates()

# Step 2: Create cross join (assign key, merge, then drop key)
universe["key"] = 1
dates["key"] = 1
universe_expanded = universe.merge(dates, on="key").drop(columns=["key"])

# Step 3: Melt df_final to long format (reshape so SECURITY_DES is a column)
df_long = df_final.melt(id_vars=["Date"], var_name="SECURITY_DES", value_name="OPT_PX")

# Step 4: Merge expanded universe with price data
universe_expanded = universe_expanded.merge(df_long, on=["SECURITY_DES", "Date"], how="left")

# Print the first few rows
universe_expanded

,id(),SECURITY_DES,EXERCISE_TYPE,EXPIRE_DT,PUT_CALL,STRIKE_PX,TICKER,Date,OPT_PX
0,BBG01RN5KQ84,G9F6C 71.38 Comdty,European,2026-01-30,Call,71.38,G9F6 Comdty,2024-09-02,NaN
1,BBG01RN5KQ84,G9F6C 71.38 Comdty,European,2026-01-30,Call,71.38,G9F6 Comdty,2024-09-03,NaN
2,BBG01RN5KQ84,G9F6C 71.38 Comdty,European,2026-01-30,Call,71.38,G9F6 Comdty,2024-09-04,NaN
3,BBG01RN5KQ84,G9F6C 71.38 Comdty,European,2026-01-30,Call,71.38,G9F6 Comdty,2024-09-05,NaN
4,BBG01RN5KQ84,G9F6C 71.38 Comdty,European,2026-01-30,Call,71.38,G9F6 Comdty,2024-09-06,NaN
...,...,...,...,...,...,...,...,...,...
45577,BBG01QLL0046,G9Z7C 75 Comdty,European,2027-12-31,Call,75.00,G9Z7 Comdty,2025-01-22,5.47
45578,BBG01QLL0046,G9Z7C 75 Comdty,European,2027-12-31,Call,75.00,G9Z7 Comdty,2025-01-23,5.45
45579,BBG01QLL0046,G9Z7C 75 Comdty,European,2027-12-31,Call,75.00,G9Z7 Comdty,2025-01-24,5.29
45580,BBG01QLL0046,G9Z7C 75 Comdty,European,2027-12-31,Call,75.00,G9Z7 Comdty,2025-01-27,5.14
45581,BBG01QLL0046,G9Z7C 75 Comdty,European,2027-12-31,Call,75.00,G9Z7 Comdty,2025-01-28,5.14

In [ ]:
# Step 5: Merge universe_expanded with df_vol on Date
universe_expanded = universe_expanded.merge(df_vol, left_on="Date", right_on="Dates", how="left").drop(columns=["Dates"])

universe_expanded

,id(),SECURITY_DES,EXERCISE_TYPE,EXPIRE_DT,PUT_CALL,STRIKE_PX,TICKER,Date,OPT_PX,HIST_PUT_IMP_VOL,VOLATILITY_30D,HIST_CALL_IMP_VOL,VOLATILITY_60D,VOLATILITY_90D,VOLATILITY_10D,VOLATILITY_20D
0,BBG01RN5KQ84,G9F6C 71.38 Comdty,European,2026-01-30,Call,71.38,G9F6 Comdty,2024-09-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,BBG01RN5KQ84,G9F6C 71.38 Comdty,European,2026-01-30,Call,71.38,G9F6 Comdty,2024-09-03,NaN,28.64,29.24,NaN,23.58,22.10,34.21,30.12
2,BBG01RN5KQ84,G9F6C 71.38 Comdty,European,2026-01-30,Call,71.38,G9F6 Comdty,2024-09-04,NaN,29.35,29.13,NaN,23.20,22.13,34.05,29.19
3,BBG01RN5KQ84,G9F6C 71.38 Comdty,European,2026-01-30,Call,71.38,G9F6 Comdty,2024-09-05,NaN,28.92,29.11,NaN,23.19,22.12,33.23,28.71
4,BBG01RN5KQ84,G9F6C 71.38 Comdty,European,2026-01-30,Call,71.38,G9F6 Comdty,2024-09-06,NaN,29.11,29.57,NaN,23.49,22.37,30.44,29.16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45577,BBG01QLL0046,G9Z7C 75 Comdty,European,2027-12-31,Call,75.00,G9Z7 Comdty,2025-01-22,5.47,20.72,20.57,20.74,26.56,28.83,30.07,22.77
45578,BBG01QLL0046,G9Z7C 75 Comdty,European,2027-12-31,Call,75.00,G9Z7 Comdty,2025-01-23,5.45,NaN,20.98,19.71,23.09,28.78,30.90,23.24
45579,BBG01QLL0046,G9Z7C 75 Comdty,European,2027-12-31,Call,75.00,G9Z7 Comdty,2025-01-24,5.29,NaN,20.25,18.95,23.07,28.71,24.68,23.01
45580,BBG01QLL0046,G9Z7C 75 Comdty,European,2027-12-31,Call,75.00,G9Z7 Comdty,2025-01-27,5.14,19.33,21.31,19.34,23.22,28.94,23.40,24.31
45581,BBG01QLL0046,G9Z7C 75 Comdty,European,2027-12-31,Call,75.00,G9Z7 Comdty,2025-01-28,5.14,NaN,21.01,18.99,23.20,28.88,24.16,24.37

In [ ]:
# use as risk free rate the U.S. 10 Year Treasury Yield from Yahoo Finance from min date to max date
import yfinance as yf

risk_free = yf.download("^TNX", start=universe_expanded["Date"].min(), end=universe_expanded["Date"].max())
risk_free

[*********************100%***********************]  1 of 1 completed

Price       Close   High    Low   Open Volume
Ticker       ^TNX   ^TNX   ^TNX   ^TNX   ^TNX
Date
2024-09-03  3.844  3.923  3.825  3.915      0
2024-09-04  3.768  3.842  3.767  3.823      0
2024-09-05  3.731  3.772  3.721  3.740      0
2024-09-06  3.710  3.761  3.648  3.708      0
2024-09-09  3.697  3.748  3.691  3.748      0
...           ...    ...    ...    ...    ...
2025-01-21  4.574  4.585  4.552  4.574      0
2025-01-22  4.599  4.617  4.560  4.560      0
2025-01-23  4.638  4.664  4.617  4.638      0
2025-01-24  4.626  4.662  4.605  4.642      0
2025-01-27  4.528  4.565  4.522  4.532      0

[100 rows x 5 columns]

In [ ]:
# add the risk free rate to the universe_expanded DataFrame
universe_expanded = universe_expanded.merge(risk_free["Close"], left_on="Date", right_index=True, how="left").rename(columns={"Close": "Risk_Free_Rate"})

In [ ]:
universe_expanded

,id(),SECURITY_DES,EXERCISE_TYPE,EXPIRE_DT,PUT_CALL,STRIKE_PX,TICKER,Date,OPT_PX,HIST_PUT_IMP_VOL,VOLATILITY_30D,HIST_CALL_IMP_VOL,VOLATILITY_60D,VOLATILITY_90D,VOLATILITY_10D,VOLATILITY_20D,^TNX
0,BBG01RN5KQ84,G9F6C 71.38 Comdty,European,2026-01-30,Call,71.38,G9F6 Comdty,2024-09-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,BBG01RN5KQ84,G9F6C 71.38 Comdty,European,2026-01-30,Call,71.38,G9F6 Comdty,2024-09-03,NaN,28.64,29.24,NaN,23.58,22.10,34.21,30.12,3.844
2,BBG01RN5KQ84,G9F6C 71.38 Comdty,European,2026-01-30,Call,71.38,G9F6 Comdty,2024-09-04,NaN,29.35,29.13,NaN,23.20,22.13,34.05,29.19,3.768
3,BBG01RN5KQ84,G9F6C 71.38 Comdty,European,2026-01-30,Call,71.38,G9F6 Comdty,2024-09-05,NaN,28.92,29.11,NaN,23.19,22.12,33.23,28.71,3.731
4,BBG01RN5KQ84,G9F6C 71.38 Comdty,European,2026-01-30,Call,71.38,G9F6 Comdty,2024-09-06,NaN,29.11,29.57,NaN,23.49,22.37,30.44,29.16,3.710
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45577,BBG01QLL0046,G9Z7C 75 Comdty,European,2027-12-31,Call,75.00,G9Z7 Comdty,2025-01-22,5.47,20.72,20.57,20.74,26.56,28.83,30.07,22.77,4.599
45578,BBG01QLL0046,G9Z7C 75 Comdty,European,2027-12-31,Call,75.00,G9Z7 Comdty,2025-01-23,5.45,NaN,20.98,19.71,23.09,28.78,30.90,23.24,4.638
45579,BBG01QLL0046,G9Z7C 75 Comdty,European,2027-12-31,Call,75.00,G9Z7 Comdty,2025-01-24,5.29,NaN,20.25,18.95,23.07,28.71,24.68,23.01,4.626
45580,BBG01QLL0046,G9Z7C 75 Comdty,European,2027-12-31,Call,75.00,G9Z7 Comdty,2025-01-27,5.14,19.33,21.31,19.34,23.22,28.94,23.40,24.31,4.528
45581,BBG01QLL0046,G9Z7C 75 Comdty,European,2027-12-31,Call,75.00,G9Z7 Comdty,2025-01-28,5.14,NaN,21.01,18.99,23.20,28.88,24.16,24.37,NaN

In [ ]:
# drop nan
universe_expanded = universe_expanded.dropna()
# rename ^TNX column to Risk_Free_Rate
universe_expanded = universe_expanded.rename(columns={"^TNX": "RISK_FREE_RATE"})
universe_expanded["RISK_FREE_RATE"] = universe_expanded["RISK_FREE_RATE"] / 100
universe_expanded

,id(),SECURITY_DES,EXERCISE_TYPE,EXPIRE_DT,PUT_CALL,STRIKE_PX,TICKER,Date,OPT_PX,HIST_PUT_IMP_VOL,VOLATILITY_30D,HIST_CALL_IMP_VOL,VOLATILITY_60D,VOLATILITY_90D,VOLATILITY_10D,VOLATILITY_20D,RISK_FREE_RATE,UNDERLYING_PRICE
435,BBG01MS5CJS3,G9F6C 76.55 Comdty,European,2026-01-30,Call,76.55,G9F6 Comdty,2024-09-11,3.21,29.77,30.13,29.77,24.94,22.90,34.63,30.34,0.03653,67.309998
441,BBG01MS5CJS3,G9F6C 76.55 Comdty,European,2026-01-30,Call,76.55,G9F6 Comdty,2024-09-19,4.09,28.12,29.19,28.11,25.66,23.55,29.14,31.54,0.03740,71.949997
442,BBG01MS5CJS3,G9F6C 76.55 Comdty,European,2026-01-30,Call,76.55,G9F6 Comdty,2024-09-20,4.01,27.79,29.09,27.77,25.64,23.52,29.36,30.41,0.03728,71.919998
449,BBG01MS5CJS3,G9F6C 76.55 Comdty,European,2026-01-30,Call,76.55,G9F6 Comdty,2024-10-01,4.24,30.42,28.91,30.37,26.61,24.34,25.42,27.15,0.03743,69.830002
450,BBG01MS5CJS3,G9F6C 76.55 Comdty,European,2026-01-30,Call,76.55,G9F6 Comdty,2024-10-02,4.41,32.30,28.66,32.28,26.62,24.33,24.38,27.15,0.03785,70.099998
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45564,BBG01QLL0046,G9Z7C 75 Comdty,European,2027-12-31,Call,75.00,G9Z7 Comdty,2025-01-03,5.47,22.11,20.09,22.11,28.11,29.91,12.47,16.46,0.04596,73.959999
45565,BBG01QLL0046,G9Z7C 75 Comdty,European,2027-12-31,Call,75.00,G9Z7 Comdty,2025-01-06,5.57,21.70,19.71,21.74,27.33,29.82,13.38,15.39,0.04618,73.559998
45567,BBG01QLL0046,G9Z7C 75 Comdty,European,2027-12-31,Call,75.00,G9Z7 Comdty,2025-01-08,5.51,22.29,17.47,22.27,27.25,29.58,15.63,15.99,0.04693,73.320000
45577,BBG01QLL0046,G9Z7C 75 Comdty,European,2027-12-31,Call,75.00,G9Z7 Comdty,2025-01-22,5.47,20.72,20.57,20.74,26.56,28.83,30.07,22.77,0.04599,75.440002
45580,BBG01QLL0046,G9Z7C 75 Comdty,European,2027-12-31,Call,75.00,G9Z7 Comdty,2025-01-27,5.14,19.33,21.31,19.34,23.22,28.94,23.40,24.31,0.04528,73.169998

In [ ]:
# from Yahoo Finance download the WTI Crude Oil price from min date to max date
wti = yf.download("CL=F", start=universe_expanded["Date"].min(), end=universe_expanded["Date"].max()+pd.Timedelta(days=1))
wti

[*********************100%***********************]  1 of 1 completed

Price           Close       High        Low       Open  Volume
Ticker           CL=F       CL=F       CL=F       CL=F    CL=F
Date
2024-09-11  67.309998  67.970001  65.629997  66.279999  393311
2024-09-12  68.970001  69.809998  67.239998  67.389999  351976
2024-09-13  68.650002  70.320000  68.470001  69.309998  308983
2024-09-16  70.089996  70.699997  68.650002  69.160004  295176
2024-09-17  71.190002  71.919998  69.610001  70.500000  251629
...               ...        ...        ...        ...     ...
2025-01-21  75.889999  78.470001  75.489998  78.190002  568807
2025-01-22  75.440002  76.449997  75.279999  75.879997  315333
2025-01-23  74.620003  76.000000  74.139999  75.389999  350688
2025-01-24  74.660004  75.209999  74.010002  74.300003  319679
2025-01-27  73.169998  75.150002  72.379997  74.540001  334418

[95 rows x 5 columns]

In [ ]:
# add the WTI Crude Oil price to the universe_expanded DataFrame
universe_expanded = universe_expanded.merge(wti["Close"], left_on="Date", right_index=True, how="left")
universe_expanded = universe_expanded.rename(columns={"CL=F": "UNDERLYING_PRICE"})

In [ ]:
universe_expanded

,id(),SECURITY_DES,EXERCISE_TYPE,EXPIRE_DT,PUT_CALL,STRIKE_PX,TICKER,Date,OPT_PX,HIST_PUT_IMP_VOL,VOLATILITY_30D,HIST_CALL_IMP_VOL,VOLATILITY_60D,VOLATILITY_90D,VOLATILITY_10D,VOLATILITY_20D,RISK_FREE_RATE,UNDERLYING_PRICE,UNDERLYING_PRICE
435,BBG01MS5CJS3,G9F6C 76.55 Comdty,European,2026-01-30,Call,76.55,G9F6 Comdty,2024-09-11,3.21,29.77,30.13,29.77,24.94,22.90,34.63,30.34,0.03653,67.309998,67.309998
441,BBG01MS5CJS3,G9F6C 76.55 Comdty,European,2026-01-30,Call,76.55,G9F6 Comdty,2024-09-19,4.09,28.12,29.19,28.11,25.66,23.55,29.14,31.54,0.03740,71.949997,71.949997
442,BBG01MS5CJS3,G9F6C 76.55 Comdty,European,2026-01-30,Call,76.55,G9F6 Comdty,2024-09-20,4.01,27.79,29.09,27.77,25.64,23.52,29.36,30.41,0.03728,71.919998,71.919998
449,BBG01MS5CJS3,G9F6C 76.55 Comdty,European,2026-01-30,Call,76.55,G9F6 Comdty,2024-10-01,4.24,30.42,28.91,30.37,26.61,24.34,25.42,27.15,0.03743,69.830002,69.830002
450,BBG01MS5CJS3,G9F6C 76.55 Comdty,European,2026-01-30,Call,76.55,G9F6 Comdty,2024-10-02,4.41,32.30,28.66,32.28,26.62,24.33,24.38,27.15,0.03785,70.099998,70.099998
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45564,BBG01QLL0046,G9Z7C 75 Comdty,European,2027-12-31,Call,75.00,G9Z7 Comdty,2025-01-03,5.47,22.11,20.09,22.11,28.11,29.91,12.47,16.46,0.04596,73.959999,73.959999
45565,BBG01QLL0046,G9Z7C 75 Comdty,European,2027-12-31,Call,75.00,G9Z7 Comdty,2025-01-06,5.57,21.70,19.71,21.74,27.33,29.82,13.38,15.39,0.04618,73.559998,73.559998
45567,BBG01QLL0046,G9Z7C 75 Comdty,European,2027-12-31,Call,75.00,G9Z7 Comdty,2025-01-08,5.51,22.29,17.47,22.27,27.25,29.58,15.63,15.99,0.04693,73.320000,73.320000
45577,BBG01QLL0046,G9Z7C 75 Comdty,European,2027-12-31,Call,75.00,G9Z7 Comdty,2025-01-22,5.47,20.72,20.57,20.74,26.56,28.83,30.07,22.77,0.04599,75.440002,75.440002
45580,BBG01QLL0046,G9Z7C 75 Comdty,European,2027-12-31,Call,75.00,G9Z7 Comdty,2025-01-27,5.14,19.33,21.31,19.34,23.22,28.94,23.40,24.31,0.04528,73.169998,73.169998

In [ ]:
# annualize the EXPIRE_DT to calculate the time to maturity
universe_expanded["EXPIRE_DT"] = pd.to_datetime(universe_expanded["EXPIRE_DT"])
universe_expanded["TIME_TO_MATURITY"] = (universe_expanded["EXPIRE_DT"] - universe_expanded["Date"]).dt.days / 365

universe_expanded

,id(),SECURITY_DES,EXERCISE_TYPE,EXPIRE_DT,PUT_CALL,STRIKE_PX,TICKER,Date,OPT_PX,HIST_PUT_IMP_VOL,VOLATILITY_30D,HIST_CALL_IMP_VOL,VOLATILITY_60D,VOLATILITY_90D,VOLATILITY_10D,VOLATILITY_20D,RISK_FREE_RATE,UNDERLYING_PRICE,UNDERLYING_PRICE,TIME_TO_MATURITY
435,BBG01MS5CJS3,G9F6C 76.55 Comdty,European,2026-01-30,Call,76.55,G9F6 Comdty,2024-09-11,3.21,29.77,30.13,29.77,24.94,22.90,34.63,30.34,0.03653,67.309998,67.309998,1.386301
441,BBG01MS5CJS3,G9F6C 76.55 Comdty,European,2026-01-30,Call,76.55,G9F6 Comdty,2024-09-19,4.09,28.12,29.19,28.11,25.66,23.55,29.14,31.54,0.03740,71.949997,71.949997,1.364384
442,BBG01MS5CJS3,G9F6C 76.55 Comdty,European,2026-01-30,Call,76.55,G9F6 Comdty,2024-09-20,4.01,27.79,29.09,27.77,25.64,23.52,29.36,30.41,0.03728,71.919998,71.919998,1.361644
449,BBG01MS5CJS3,G9F6C 76.55 Comdty,European,2026-01-30,Call,76.55,G9F6 Comdty,2024-10-01,4.24,30.42,28.91,30.37,26.61,24.34,25.42,27.15,0.03743,69.830002,69.830002,1.331507
450,BBG01MS5CJS3,G9F6C 76.55 Comdty,European,2026-01-30,Call,76.55,G9F6 Comdty,2024-10-02,4.41,32.30,28.66,32.28,26.62,24.33,24.38,27.15,0.03785,70.099998,70.099998,1.328767
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45564,BBG01QLL0046,G9Z7C 75 Comdty,European,2027-12-31,Call,75.00,G9Z7 Comdty,2025-01-03,5.47,22.11,20.09,22.11,28.11,29.91,12.47,16.46,0.04596,73.959999,73.959999,2.991781
45565,BBG01QLL0046,G9Z7C 75 Comdty,European,2027-12-31,Call,75.00,G9Z7 Comdty,2025-01-06,5.57,21.70,19.71,21.74,27.33,29.82,13.38,15.39,0.04618,73.559998,73.559998,2.983562
45567,BBG01QLL0046,G9Z7C 75 Comdty,European,2027-12-31,Call,75.00,G9Z7 Comdty,2025-01-08,5.51,22.29,17.47,22.27,27.25,29.58,15.63,15.99,0.04693,73.320000,73.320000,2.978082
45577,BBG01QLL0046,G9Z7C 75 Comdty,European,2027-12-31,Call,75.00,G9Z7 Comdty,2025-01-22,5.47,20.72,20.57,20.74,26.56,28.83,30.07,22.77,0.04599,75.440002,75.440002,2.939726
45580,BBG01QLL0046,G9Z7C 75 Comdty,European,2027-12-31,Call,75.00,G9Z7 Comdty,2025-01-27,5.14,19.33,21.31,19.34,23.22,28.94,23.40,24.31,0.04528,73.169998,73.169998,2.926027